import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import { StateContext } from "@/context/theme";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Symbol Audio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
          <Toaster position="top-left" reverseOrder={false} />
          <NavBar />
          {children}
        </StateContext>
      </body>
    </html>
  );
}
